### ISSUE TITLE
Gnome 3.18

### ISSUE THREAD

**Issue by MarPiRK** [awamper/text-translator#22]
It'd be nice to add support for new Gnome 3.18 found in Fedora 23 Beta.

**Comment by djmaze** [comment]
Adding 3.18 in `metadata.json` seems to not be enough. The shell immediately crashes for me when trying to enable the extension.

**Comment by MarPiRK** [comment]
That's why I submitted this issue.

**Comment by mudongliang** [comment]
I will check this version in my newly upgraded Arch.

**Comment by talesam** [comment]
Please, who is responsible for this extension, upgrade to work in gnome 3.18 !!

**Comment by caglarbingol** [comment]
please upgrade. i need it too

2015-11-06 4:46 GMT+03:00 Tales A. Mendonça <notifications@github.com>:

**Comment by awamper** [comment]
7a04810
